name: manga_easy_lint_rules
description: Um lib com as regras de lint da Manga easy.
version: 1.1.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  analyzer: ^6.8.0
  custom_lint_builder: ^0.6.7
  flutter_lints: ^5.0.0
