name: manga_easy_lint_rules
description: Um lib com as regras de lint da Manga easy.
version: 1.1.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^5.7.0
  custom_lint_builder: ^0.5.0


dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
