name: exemple
description: exemple.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: ^5.12.0
  analyzer_plugin: ^0.11.2
  # custom_lint_test_builder will give us tools for writing lints
  custom_lint_builder: ^0.4.0


dev_dependencies:
  custom_lint: 0.4.0
  manga_easy_lint_rules:
    git:
      url: https://github.com/manga-easy/manga_easy_lint_rules.git
      ref: v1.0.0
